# https://github.com/cachix/devenv/blob/2a399e9ea5e981f225d75b25c8fa8d76f730131d/docs/src/content/docs/integrations/github-actions.md?plain=1#L127-L159
name: "Test"

on:
  pull_request:
  push:

jobs:
  tests:
    strategy:
      matrix:
        os: [macos-26, ubuntu-24.04]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile add nixpkgs/b8030c58deafc013fc51791377fe8fea4dadcb00#devenv

      - name: Build the devenv shell and run any pre-commit hooks
        run: devenv test

      - name: Run a single command in the devenv shell
        run: devenv shell hello
